/**
 * Downloads the photos listed in content/photos/sources.json (freely licensed
 * stock photos or the restaurant's own), checks they are real images, and
 * writes content/photos/CREDITS.md. Files already present are skipped, so
 * replacing a photo is just: delete it (or change its entry) and run again.
 *
 *   npm run photos:fetch            # download what's missing
 *   npm run photos:fetch -- --force # download everything again
 *
 * Entries:
 *   { "file": "hero.jpg", "url": "https://…", "page": "https://…",
 *     "author": "…", "license": "Unsplash License", "use": "hero" }
 * `file` is relative to content/photos/. Page photos live at the top level
 * (hero, story, gallery…); dish photos for the sample menu live in menu/
 * (see server/seed/demo.ts).
 */
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

type Source = { file: string; url: string; page?: string; author?: string; license: string; use?: string };

const ROOT = path.resolve('content/photos');
const MANIFEST = path.join(ROOT, 'sources.json');
const force = process.argv.includes('--force');

async function download(src: Source): Promise<'ok' | 'skipped'> {
  const target = path.join(ROOT, src.file);
  if (!path.resolve(target).startsWith(ROOT + path.sep)) throw new Error(`${src.file}: must stay inside content/photos`);
  if (!force && fs.existsSync(target)) return 'skipped';
  const res = await fetch(src.url, { redirect: 'follow', signal: AbortSignal.timeout(60_000) });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  const meta = await sharp(buffer).metadata(); // throws if it isn't an image
  const min = src.file.startsWith('menu/') ? 600 : 1000;
  if ((meta.width ?? 0) < min) throw new Error(`only ${meta.width}px wide (need ${min}px+)`);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  // Re-encode as JPEG without metadata (no EXIF/GPS), capped in size so the repository stays light.
  await sharp(buffer)
    .rotate()
    .resize({ width: src.file.startsWith('menu/') ? 1600 : 2400, withoutEnlargement: true })
    .jpeg({ quality: 88, mozjpeg: true })
    .toFile(target);
  return 'ok';
}

function credits(sources: Source[]): string {
  const lines = sources.map((s) => {
    const who = s.author ? ` — ${s.author}` : '';
    const where = s.page ? ` ([source](${s.page}))` : '';
    return `- \`${s.file}\`${who}, ${s.license}${where}${s.use ? ` · used for: ${s.use}` : ''}`;
  });
  return `# Photo credits\n\nGenerated by \`npm run photos:fetch\` from \`sources.json\`. Keep this file with the photos.\n\n${lines.join('\n')}\n`;
}

async function main() {
  if (!fs.existsSync(MANIFEST)) {
    console.log('No content/photos/sources.json — nothing to download.');
    return;
  }
  const { photos } = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')) as { photos: Source[] };
  let failed = 0;
  for (const src of photos) {
    try {
      const result = await download(src);
      console.log(`${result === 'ok' ? '✓' : '·'} ${src.file}${result === 'skipped' ? ' (already here)' : ''}`);
    } catch (err) {
      failed++;
      const reason = err instanceof Error ? (err.cause instanceof Error ? `${err.message}: ${err.cause.message}` : err.message) : String(err);
      console.error(`✗ ${src.file} ← ${src.url}\n    ${reason}`);
    }
  }
  fs.writeFileSync(path.join(ROOT, 'CREDITS.md'), credits(photos));
  if (failed > 0) {
    console.error(`\n${failed} photo(s) could not be downloaded. If every download fails, the network may be blocking the photo hosts.`);
    process.exitCode = 1;
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
