/* eslint-disable max-lines */
import { useI18n } from '@/i18n';

const fr = {
  // Shell
  dashboard: 'Espace équipe',
  live: 'En direct',
  reconnecting: 'Reconnexion…',
  soundOn: 'Son activé',
  soundOff: 'Son coupé',
  enableSound: 'Activer le son des nouvelles commandes',
  viewSite: 'Voir le site',
  signOut: 'Se déconnecter',
  myPassword: 'Mon mot de passe',
  sessionExpired: 'Session expirée — merci de vous reconnecter.',
  nav: {
    reservations: 'Réservations',
    orders: 'Commandes',
    tables: 'Tables & QR',
    menu: 'Carte',
    settings: 'Réglages',
    team: 'Équipe',
  },
  adminOnly: 'Réservé aux administrateurs.',
  saved: 'Modifications enregistrées',
  unlimited: 'Illimité',
  minutes: 'min',
  days: 'jours',
  people: 'pers.',
  optional: 'facultatif',
  confirmTitle: 'Confirmer',
  yes: 'Oui',
  no: 'Non',
  cancel: 'Annuler',
  save: 'Enregistrer',
  delete: 'Supprimer',
  edit: 'Modifier',
  add: 'Ajouter',
  close: 'Fermer',
  loading: 'Chargement…',
  none: '—',
  search: 'Rechercher',
  error: 'Une erreur est survenue.',

  // Login
  login: {
    title: 'Connexion équipe',
    intro: 'Accès réservé à l’équipe de B&B Park.',
    email: 'E-mail',
    password: 'Mot de passe',
    submit: 'Se connecter',
    back: 'Retour au site',
  },

  // Reservations
  res: {
    title: 'Réservations',
    newReservation: 'Nouvelle réservation',
    newRequest: 'Nouvelle demande de réservation',
    tabDay: 'Planning',
    tabPending: 'À confirmer',
    tabSearch: 'Recherche',
    today: 'Aujourd’hui',
    previousDay: 'Jour précédent',
    nextDay: 'Jour suivant',
    summary: (n: number, covers: number) => `${n} réservation${n > 1 ? 's' : ''} · ${covers} couvert${covers > 1 ? 's' : ''}`,
    showAll: 'Afficher aussi annulées / refusées',
    empty: 'Aucune réservation.',
    emptyPending: 'Aucune demande en attente. 🎉',
    searchPlaceholder: 'Nom, téléphone, e-mail ou référence',
    status: {
      pending: 'À confirmer',
      confirmed: 'Confirmée',
      seated: 'Installée',
      completed: 'Terminée',
      declined: 'Refusée',
      cancelled: 'Annulée',
      no_show: 'Non venue',
    },
    source: { web: 'En ligne', phone: 'Téléphone', walk_in: 'Sur place', staff: 'Équipe' } as Record<string, string>,
    actions: {
      confirm: 'Confirmer',
      decline: 'Refuser',
      seat: 'Installée',
      complete: 'Terminée',
      cancel: 'Annuler',
      noShow: 'Non venue',
      reopen: 'Rouvrir',
    },
    confirmDecline: 'Refuser cette demande de réservation ?',
    confirmCancel: 'Annuler cette réservation ?',
    confirmNoShow: 'Marquer comme non venue ?',
    table: 'Table',
    assignTable: 'Attribuer une table',
    noTable: 'Sans table',
    seats: (n: number) => `${n} pl.`,
    conflict: (list: string) => `Attention : table déjà attribuée à ${list} sur ce créneau.`,
    notes: 'Demande du client',
    staffNote: 'Note interne',
    staffNotePlaceholder: 'Visible uniquement par l’équipe',
    reference: 'Réf.',
    created: 'Reçue',
    contact: 'Prévenir',
    call: 'Appeler',
    sms: 'SMS',
    whatsapp: 'WhatsApp',
    messageConfirmed: (name: string, date: string, time: string, n: number) =>
      `Bonjour ${name}, votre réservation chez B&B Park le ${date} à ${time} pour ${n} personne${n > 1 ? 's' : ''} est confirmée. À bientôt !`,
    messageDeclined: (name: string, date: string, time: string) =>
      `Bonjour ${name}, nous sommes désolés : nous ne pouvons pas vous accueillir le ${date} à ${time}. N’hésitez pas à nous contacter pour un autre créneau.`,
    form: {
      title: 'Nouvelle réservation',
      name: 'Nom',
      phone: 'Téléphone',
      email: 'E-mail',
      date: 'Date',
      time: 'Heure',
      party: 'Couverts',
      notes: 'Demande du client',
      status: 'Statut',
      source: 'Origine',
      ignoreCapacity: 'Autoriser au-delà de la capacité en ligne (réservation téléphonique)',
      slotsHint: 'Créneaux disponibles en ligne',
      submit: 'Enregistrer la réservation',
      created: 'Réservation enregistrée',
    },
  },

  // Orders
  orders: {
    title: 'Commandes',
    accepting: 'Commandes à table',
    acceptingOn: 'Activées',
    acceptingOff: 'En pause',
    pausedNotice: 'Les clients ne peuvent pas envoyer de commande pour le moment.',
    tabOpen: 'En cours',
    tabToday: 'Aujourd’hui',
    columns: { received: 'Nouvelles', preparing: 'En préparation', ready: 'Prêtes' },
    status: { received: 'Nouvelle', preparing: 'En préparation', ready: 'Prête', served: 'Servie', cancelled: 'Annulée' },
    next: { received: 'Commencer', preparing: 'Prête', ready: 'Servie' } as Record<string, string>,
    back: 'Revenir en arrière',
    cancelOrder: 'Annuler la commande',
    confirmCancel: 'Annuler cette commande ?',
    table: (n: string) => `Table ${n}`,
    ago: (m: number) => (m < 1 ? 'à l’instant' : `il y a ${m} min`),
    empty: 'Aucune commande en cours.',
    emptyToday: 'Aucune commande aujourd’hui.',
    total: 'Total',
    note: 'Remarque',
    summary: (n: number, total: string) => `${n} commande${n > 1 ? 's' : ''} · ${total}`,
    time: 'Heure',
    items: 'Articles',
    newOrder: (table: string) => `Nouvelle commande — table ${table}`,
  },

  // Tables
  tables: {
    title: 'Tables & QR codes',
    intro: 'Chaque table possède un QR code unique : en le scannant, le client ouvre la carte avec sa table déjà identifiée.',
    add: 'Ajouter une table',
    print: 'Imprimer les QR codes',
    number: 'Numéro / nom affiché',
    numberHint: 'Tel qu’indiqué sur la table (ex. 8, T8, Terrasse 2).',
    seats: 'Places',
    area: 'Zone',
    areaPlaceholder: 'Salle, terrasse…',
    active: 'Active',
    inactive: 'Inactive',
    activate: 'Activer',
    deactivate: 'Désactiver',
    qr: 'QR code',
    link: 'Lien',
    copy: 'Copier le lien',
    copied: 'Lien copié',
    downloadSvg: 'Télécharger (SVG)',
    downloadPng: 'Télécharger (PNG)',
    regenerate: 'Générer un nouveau QR code',
    confirmRegenerate: 'Les QR codes déjà imprimés pour cette table ne fonctionneront plus. Continuer ?',
    regenerated: 'Nouveau QR code généré',
    confirmDelete: (n: string) => `Supprimer la table ${n} ?`,
    general: 'QR code général',
    generalHint: 'Pour l’entrée ou la vitrine : le client ouvre la carte puis saisit le numéro de sa table.',
    publicUrlWarning: (origin: string) =>
      `Les QR codes pointent vers ${origin}. Définissez PUBLIC_URL (adresse publique du site) avant d’imprimer les QR codes définitifs.`,
    empty: 'Aucune table. Ajoutez vos tables pour générer leurs QR codes.',
    editTitle: 'Modifier la table',
    newTitle: 'Nouvelle table',
  },

  // Print sheet
  print: {
    title: 'QR codes des tables',
    printNow: 'Imprimer',
    back: 'Retour',
    scan: 'Scannez pour consulter la carte et commander',
    scanEn: 'Scan to view the menu & order',
    fallback: (host: string, n: string) => `Pas de QR ? Allez sur ${host}/table et saisissez le numéro ${n}.`,
    generalTitle: 'Commander à table',
    generalFallback: (host: string) => `Ou rendez-vous sur ${host}/table`,
  },

  // Menu
  menu: {
    title: 'Carte',
    addCategory: 'Nouvelle catégorie',
    addItem: 'Nouveau plat',
    demoNotice: 'Le menu d’exemple est chargé (plats et prix fictifs). Supprimez-le avant de saisir la vraie carte.',
    removeDemo: 'Supprimer le menu d’exemple',
    confirmRemoveDemo: 'Supprimer tous les plats et catégories du menu d’exemple ?',
    available: 'Disponible',
    soldOut: 'Épuisé',
    visible: 'Visible sur la carte',
    hidden: 'Masqué',
    special: 'Suggestion du chef',
    moveUp: 'Monter',
    moveDown: 'Descendre',
    emptyCategory: 'Aucun plat dans cette catégorie.',
    empty: 'La carte est vide. Commencez par créer une catégorie.',
    confirmDeleteItem: (n: string) => `Supprimer « ${n} » ?`,
    confirmDeleteCategory: (n: string) => `Supprimer la catégorie « ${n} » et tous ses plats ?`,
    category: {
      newTitle: 'Nouvelle catégorie',
      editTitle: 'Modifier la catégorie',
      name: 'Nom (français)',
      nameEn: 'Name (English)',
      description: 'Description (français)',
      descriptionEn: 'Description (English)',
      visible: 'Visible sur la carte',
    },
    item: {
      newTitle: 'Nouveau plat',
      editTitle: 'Modifier le plat',
      photo: 'Photo',
      upload: 'Choisir une photo',
      replace: 'Remplacer',
      removePhoto: 'Retirer la photo',
      uploading: 'Envoi de la photo…',
      photoHint: 'JPEG, PNG ou WebP, 12 Mo max. Recadrée automatiquement.',
      name: 'Nom (français)',
      nameEn: 'Name (English)',
      description: 'Description (français)',
      descriptionEn: 'Description (English)',
      price: 'Prix (DH)',
      category: 'Catégorie',
      dietary: 'Régimes & allergènes',
      options: 'Options & suppléments',
      addGroup: 'Ajouter un groupe d’options',
      groupName: 'Nom du groupe (FR)',
      groupNameEn: 'Group name (EN)',
      groupType: 'Type de choix',
      types: {
        one_required: 'Un choix obligatoire',
        one_optional: 'Un choix facultatif',
        many_optional: 'Plusieurs choix facultatifs',
      },
      optionName: 'Option (FR)',
      optionNameEn: 'Option (EN)',
      optionPrice: 'Supplément (DH)',
      addOption: 'Ajouter une option',
      removeGroup: 'Supprimer le groupe',
      flags: 'Affichage',
      created: 'Plat ajouté',
    },
  },

  // Settings
  settings: {
    title: 'Réglages',
    booking: 'Réservations en ligne',
    bookingIntro: 'Ces règles déterminent les créneaux proposés aux clients.',
    onlineEnabled: 'Accepter les réservations en ligne',
    requireApproval: 'Confirmation manuelle par l’équipe',
    requireApprovalHint:
      'Activé : chaque demande reste « à confirmer » jusqu’à votre validation. Désactivé : confirmation automatique dans la limite des capacités ci-dessous.',
    slotInterval: 'Intervalle entre les créneaux',
    duration: 'Durée moyenne d’un repas',
    minNotice: 'Délai minimum avant l’arrivée',
    maxDaysAhead: 'Réservation possible jusqu’à',
    maxPartySize: 'Taille maximale d’un groupe en ligne',
    maxCoversPerSlot: 'Couverts max. arrivant sur un même créneau',
    maxConcurrentCovers: 'Couverts max. en salle en même temps (réservations en ligne)',
    lastSeating: 'Dernière arrivée avant la fermeture',
    timeZone: 'Fuseau horaire',
    unlimitedHint: 'Laisser vide = illimité',
    hours: 'Horaires d’ouverture',
    hoursIntro: 'Affichés sur le site et utilisés pour les créneaux. Une fermeture après minuit est possible (ex. 19:00 – 01:00).',
    open: 'Ouvert',
    closed: 'Fermé',
    addRange: 'Ajouter une plage',
    copyToAll: 'Appliquer à tous les jours ouverts',
    special: 'Fermetures & horaires exceptionnels',
    specialIntro: 'Jours fériés, événements privés, horaires spéciaux…',
    addSpecial: 'Ajouter',
    specialDate: 'Date',
    specialClosed: 'Fermé toute la journée',
    specialNote: 'Note (affichée sur le site)',
    noSpecial: 'Aucun jour exceptionnel.',
    ordering: 'Commande à table',
    orderingEnabled: 'Autoriser les commandes depuis la table',
    orderingOnlyOpen: 'Uniquement pendant les heures d’ouverture',
    preview: 'Aperçu des créneaux',
    previewFor: (date: string) => `Créneaux en ligne pour le ${date} (2 personnes)`,
    noSlots: 'Aucun créneau ce jour-là.',
  },

  // Team
  team: {
    title: 'Équipe',
    intro: 'Les administrateurs gèrent la carte, les tables et les réglages. L’équipe gère les réservations et les commandes.',
    add: 'Ajouter un membre',
    name: 'Nom',
    email: 'E-mail',
    role: 'Rôle',
    roles: { admin: 'Administrateur', staff: 'Équipe' } as Record<string, string>,
    password: 'Mot de passe provisoire',
    passwordHint: 'Au moins 10 caractères. À communiquer de vive voix.',
    active: 'Actif',
    inactive: 'Désactivé',
    lastLogin: 'Dernière connexion',
    never: 'Jamais',
    deactivate: 'Désactiver',
    activate: 'Réactiver',
    resetPassword: 'Nouveau mot de passe',
    you: 'vous',
    created: 'Compte créé',
    changePassword: 'Changer mon mot de passe',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    passwordChanged: 'Mot de passe modifié',
  },
};

export type StaffStrings = typeof fr;

const en: StaffStrings = {
  dashboard: 'Staff area',
  live: 'Live',
  reconnecting: 'Reconnecting…',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  enableSound: 'Play a sound for new orders',
  viewSite: 'View website',
  signOut: 'Sign out',
  myPassword: 'My password',
  sessionExpired: 'Session expired — please sign in again.',
  nav: {
    reservations: 'Reservations',
    orders: 'Orders',
    tables: 'Tables & QR',
    menu: 'Menu',
    settings: 'Settings',
    team: 'Team',
  },
  adminOnly: 'Administrators only.',
  saved: 'Changes saved',
  unlimited: 'Unlimited',
  minutes: 'min',
  days: 'days',
  people: 'ppl',
  optional: 'optional',
  confirmTitle: 'Confirm',
  yes: 'Yes',
  no: 'No',
  cancel: 'Cancel',
  save: 'Save',
  delete: 'Delete',
  edit: 'Edit',
  add: 'Add',
  close: 'Close',
  loading: 'Loading…',
  none: '—',
  search: 'Search',
  error: 'Something went wrong.',

  login: {
    title: 'Staff sign-in',
    intro: 'For the B&B Park team only.',
    email: 'E-mail',
    password: 'Password',
    submit: 'Sign in',
    back: 'Back to website',
  },

  res: {
    title: 'Reservations',
    newReservation: 'New reservation',
    newRequest: 'New reservation request',
    tabDay: 'Schedule',
    tabPending: 'To confirm',
    tabSearch: 'Search',
    today: 'Today',
    previousDay: 'Previous day',
    nextDay: 'Next day',
    summary: (n: number, covers: number) => `${n} reservation${n > 1 ? 's' : ''} · ${covers} cover${covers > 1 ? 's' : ''}`,
    showAll: 'Also show cancelled / declined',
    empty: 'No reservations.',
    emptyPending: 'No pending requests. 🎉',
    searchPlaceholder: 'Name, phone, e-mail or reference',
    status: {
      pending: 'To confirm',
      confirmed: 'Confirmed',
      seated: 'Seated',
      completed: 'Completed',
      declined: 'Declined',
      cancelled: 'Cancelled',
      no_show: 'No-show',
    },
    source: { web: 'Online', phone: 'Phone', walk_in: 'Walk-in', staff: 'Staff' },
    actions: {
      confirm: 'Confirm',
      decline: 'Decline',
      seat: 'Seated',
      complete: 'Completed',
      cancel: 'Cancel',
      noShow: 'No-show',
      reopen: 'Reopen',
    },
    confirmDecline: 'Decline this reservation request?',
    confirmCancel: 'Cancel this reservation?',
    confirmNoShow: 'Mark as no-show?',
    table: 'Table',
    assignTable: 'Assign a table',
    noTable: 'No table',
    seats: (n: number) => `${n} seats`,
    conflict: (list: string) => `Warning: table already assigned to ${list} at this time.`,
    notes: 'Guest request',
    staffNote: 'Internal note',
    staffNotePlaceholder: 'Only visible to staff',
    reference: 'Ref.',
    created: 'Received',
    contact: 'Notify',
    call: 'Call',
    sms: 'SMS',
    whatsapp: 'WhatsApp',
    messageConfirmed: (name: string, date: string, time: string, n: number) =>
      `Hello ${name}, your table at B&B Park on ${date} at ${time} for ${n} is confirmed. See you soon!`,
    messageDeclined: (name: string, date: string, time: string) =>
      `Hello ${name}, we are sorry: we cannot seat you on ${date} at ${time}. Please contact us for another time.`,
    form: {
      title: 'New reservation',
      name: 'Name',
      phone: 'Phone',
      email: 'E-mail',
      date: 'Date',
      time: 'Time',
      party: 'Guests',
      notes: 'Guest request',
      status: 'Status',
      source: 'Source',
      ignoreCapacity: 'Allow beyond online capacity (phone booking)',
      slotsHint: 'Online availability',
      submit: 'Save reservation',
      created: 'Reservation saved',
    },
  },

  orders: {
    title: 'Orders',
    accepting: 'Table ordering',
    acceptingOn: 'On',
    acceptingOff: 'Paused',
    pausedNotice: 'Guests cannot send orders right now.',
    tabOpen: 'In progress',
    tabToday: 'Today',
    columns: { received: 'New', preparing: 'Preparing', ready: 'Ready' },
    status: { received: 'New', preparing: 'Preparing', ready: 'Ready', served: 'Served', cancelled: 'Cancelled' },
    next: { received: 'Start', preparing: 'Ready', ready: 'Served' },
    back: 'Move back',
    cancelOrder: 'Cancel order',
    confirmCancel: 'Cancel this order?',
    table: (n: string) => `Table ${n}`,
    ago: (m: number) => (m < 1 ? 'just now' : `${m} min ago`),
    empty: 'No orders in progress.',
    emptyToday: 'No orders today.',
    total: 'Total',
    note: 'Note',
    summary: (n: number, total: string) => `${n} order${n > 1 ? 's' : ''} · ${total}`,
    time: 'Time',
    items: 'Items',
    newOrder: (table: string) => `New order — table ${table}`,
  },

  tables: {
    title: 'Tables & QR codes',
    intro: 'Each table has its own QR code: scanning it opens the menu with the table already identified.',
    add: 'Add a table',
    print: 'Print QR codes',
    number: 'Number / label shown',
    numberHint: 'As shown on the table (e.g. 8, T8, Terrace 2).',
    seats: 'Seats',
    area: 'Area',
    areaPlaceholder: 'Dining room, terrace…',
    active: 'Active',
    inactive: 'Inactive',
    activate: 'Activate',
    deactivate: 'Deactivate',
    qr: 'QR code',
    link: 'Link',
    copy: 'Copy link',
    copied: 'Link copied',
    downloadSvg: 'Download (SVG)',
    downloadPng: 'Download (PNG)',
    regenerate: 'Generate a new QR code',
    confirmRegenerate: 'QR codes already printed for this table will stop working. Continue?',
    regenerated: 'New QR code generated',
    confirmDelete: (n: string) => `Delete table ${n}?`,
    general: 'General QR code',
    generalHint: 'For the entrance or window: guests open the menu, then enter their table number.',
    publicUrlWarning: (origin: string) =>
      `QR codes point to ${origin}. Set PUBLIC_URL (the public address of the site) before printing final QR codes.`,
    empty: 'No tables yet. Add your tables to generate their QR codes.',
    editTitle: 'Edit table',
    newTitle: 'New table',
  },

  print: {
    title: 'Table QR codes',
    printNow: 'Print',
    back: 'Back',
    scan: 'Scannez pour consulter la carte et commander',
    scanEn: 'Scan to view the menu & order',
    fallback: (host: string, n: string) => `No QR? Go to ${host}/table and enter number ${n}.`,
    generalTitle: 'Order at your table',
    generalFallback: (host: string) => `Or go to ${host}/table`,
  },

  menu: {
    title: 'Menu',
    addCategory: 'New category',
    addItem: 'New dish',
    demoNotice: 'The sample menu is loaded (made-up dishes and prices). Remove it before entering the real menu.',
    removeDemo: 'Remove sample menu',
    confirmRemoveDemo: 'Remove every dish and category of the sample menu?',
    available: 'Available',
    soldOut: 'Sold out',
    visible: 'Shown on the menu',
    hidden: 'Hidden',
    special: 'Chef’s special',
    moveUp: 'Move up',
    moveDown: 'Move down',
    emptyCategory: 'No dishes in this category.',
    empty: 'The menu is empty. Start by creating a category.',
    confirmDeleteItem: (n: string) => `Delete “${n}”?`,
    confirmDeleteCategory: (n: string) => `Delete the “${n}” category and all its dishes?`,
    category: {
      newTitle: 'New category',
      editTitle: 'Edit category',
      name: 'Name (French)',
      nameEn: 'Name (English)',
      description: 'Description (French)',
      descriptionEn: 'Description (English)',
      visible: 'Shown on the menu',
    },
    item: {
      newTitle: 'New dish',
      editTitle: 'Edit dish',
      photo: 'Photo',
      upload: 'Choose a photo',
      replace: 'Replace',
      removePhoto: 'Remove photo',
      uploading: 'Uploading photo…',
      photoHint: 'JPEG, PNG or WebP, 12 MB max. Cropped automatically.',
      name: 'Name (French)',
      nameEn: 'Name (English)',
      description: 'Description (French)',
      descriptionEn: 'Description (English)',
      price: 'Price (DH)',
      category: 'Category',
      dietary: 'Diets & allergens',
      options: 'Options & extras',
      addGroup: 'Add an option group',
      groupName: 'Group name (FR)',
      groupNameEn: 'Group name (EN)',
      groupType: 'Choice type',
      types: {
        one_required: 'One required choice',
        one_optional: 'One optional choice',
        many_optional: 'Several optional choices',
      },
      optionName: 'Option (FR)',
      optionNameEn: 'Option (EN)',
      optionPrice: 'Extra (DH)',
      addOption: 'Add an option',
      removeGroup: 'Remove group',
      flags: 'Display',
      created: 'Dish added',
    },
  },

  settings: {
    title: 'Settings',
    booking: 'Online reservations',
    bookingIntro: 'These rules decide which times guests can book.',
    onlineEnabled: 'Accept online reservations',
    requireApproval: 'Manual confirmation by staff',
    requireApprovalHint:
      'On: every request stays “to confirm” until you accept it. Off: bookings are confirmed automatically within the capacity limits below.',
    slotInterval: 'Time between slots',
    duration: 'Average meal duration',
    minNotice: 'Minimum notice before arrival',
    maxDaysAhead: 'Bookable up to',
    maxPartySize: 'Largest party bookable online',
    maxCoversPerSlot: 'Max guests arriving in the same slot',
    maxConcurrentCovers: 'Max guests seated at once (online bookings)',
    lastSeating: 'Last arrival before closing',
    timeZone: 'Time zone',
    unlimitedHint: 'Leave empty = unlimited',
    hours: 'Opening hours',
    hoursIntro: 'Shown on the website and used for booking slots. Closing after midnight is supported (e.g. 19:00 – 01:00).',
    open: 'Open',
    closed: 'Closed',
    addRange: 'Add a time range',
    copyToAll: 'Apply to every open day',
    special: 'Closures & special hours',
    specialIntro: 'Public holidays, private events, special hours…',
    addSpecial: 'Add',
    specialDate: 'Date',
    specialClosed: 'Closed all day',
    specialNote: 'Note (shown on the website)',
    noSpecial: 'No special days.',
    ordering: 'Table ordering',
    orderingEnabled: 'Allow ordering from the table',
    orderingOnlyOpen: 'Only during opening hours',
    preview: 'Slot preview',
    previewFor: (date: string) => `Online slots on ${date} (2 guests)`,
    noSlots: 'No slots that day.',
  },

  team: {
    title: 'Team',
    intro: 'Administrators manage the menu, tables and settings. Staff manage reservations and orders.',
    add: 'Add a member',
    name: 'Name',
    email: 'E-mail',
    role: 'Role',
    roles: { admin: 'Administrator', staff: 'Staff' },
    password: 'Temporary password',
    passwordHint: 'At least 10 characters. Share it in person.',
    active: 'Active',
    inactive: 'Deactivated',
    lastLogin: 'Last sign-in',
    never: 'Never',
    deactivate: 'Deactivate',
    activate: 'Reactivate',
    resetPassword: 'New password',
    you: 'you',
    created: 'Account created',
    changePassword: 'Change my password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    passwordChanged: 'Password changed',
  },
};

export function useStaffT(): StaffStrings {
  return useI18n().lang === 'en' ? en : fr;
}

/** Strings in a given language (e.g. to message a guest in the language they booked in). */
export const staffStringsFor = (lang: 'fr' | 'en'): StaffStrings => (lang === 'en' ? en : fr);
